services:
  miakapp-server:
    image: miakapp-server:development
    build: .
    container_name: miakapp-server
    environment:
      MIAKAPP_ALLOWED_ORIGINS: ${MIAKAPP_ALLOWED_ORIGINS:-}
      MIAKAPP_LISTEN_ADDRESS: :3000
    ports:
      - '3000:3000'
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
